package test.xml.interfaces;

import org.xml.sax.Attributes;

/**
 * Includes all methods needed by the XMLParser to correctly stream through
 * some xml and pass it to a corosponding handler that knows the specifics
 * of what the xml should look like
 */
public interface ParsingStrategy {

	/**
	 * Called when a new opening tag is processed
	 *
	 * @param k The tag name/key
	 */
	public void setNextKey(String k);


	/**
	 * Called right after setNextKey to provide the attributes that were found
	 * inside the tag
	 *
	 * @param a The attribute object generated by SAX
	 * TODO: Convert this to take a hashmap to root out SAX specific stuff?
	 */
	public void setNextAttribute(Attributes a);


	/**
	 * Called on the content between an opening and closing tag
	 *
	 * @param v The inner value of the tag
	 */
	public void setNextValue(String v);


	/**
	 * Signals that a closing tag was processed
	 */
	public void setKeyEnd();


	/**
	 * Returns (or creates and returns) the data transfer object that was
	 * the intended outcome of a particular parsing strategy
	 *
	 * @return The DTO for use by the application
	 */
	public DTO getDTO();

}

